name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate on Github
        run: echo "//maven.pkg.github.com/ontological-behavior-modeling/omgutil:_authToken=${{secrets.GITHUB_TOKEN}}" >> -/.npmrc
          
      - name: Release
        run: |
          mvn -B release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
