name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Checkout Code
        uses: actions/checkout@v2
          
      - name: Publish package
        run: |
          mvn -B release:clean release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
