name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main
  
jobs:
  release:
    runs-on: ubuntu-latest

    steps:        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name: Copy settings.xml
        run: cp ./.github/Maven/settings.xml $HOME/.m2/settings.xml
       
      - name: Release Prepare
        run: |
          mvn release:clean release:prepare -B
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}

      - name: Release Perform
        run: |
          mvn release:perform -B
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
